- hosts: cassandra
  any_errors_fatal: true
  environment: "{{ proxy_env | default({}) }}"
  vars:
    cassandra_keyspaces:
      - brig
      - galley
      - gundeck
      - spar
    # cassandra 3.11 doesn't support java 11 yet, use openjdk-8.
    java_packages:
      - openjdk-8-jdk
  roles:
    - role: hostname
      tags:
        - hostname

    - role: ansible-role-ntp
      when: not offline
      tags:
        - ntp

    # This role is fine for offline; doesn't need configuring. Only apt
    # installs
    - role: ansible-role-java
      tags:
        - java

    - role: ansible-cassandra
      tags:
        - cassandra

    - role: ansible-ntp-verify
      when: not offline
      tags:
        - ntp
  tasks:
    # these are optional debug tasks to see that the cluster has come up sucessfully
    - shell: nodetool status
      register: nodetool_status
      tags:
        - cassandra
        - debug
    - debug: var=nodetool_status.stdout_lines
      tags:
        - cassandra
        - debug
