---
- hosts: etcd
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - etcd-helpers

- hosts: k8s-cluster
  tasks:
    - name: Annotate nodes
      command: "kubectl annotate node --overwrite {{ inventory_hostname }} {{ item.key }}={{ item.value }}"
      when: node_annotations is defined
      with_dict: "{{ node_annotations }}"
- name: Bootstrap cluster
  import_playbook: roles-external/kubespray/cluster.yml


- import_playbook: kubernetes_logging.yml
