# Fetch the `kubeconfig` file. This is useful when the original `kubeconfig` has
# been lost.
# Run it with e.g. `ENV=bella make create-inventory fetch-kubeconfig`.

- name: 'Fetch kubeconfig'
  hosts: kube-master
  tasks:
    - name: download kubeconfig
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kubeconfig.new
        flat: true

    - name: notify user about kubeconfig
      ansible.builtin.debug:
        msg:
          - "./kubeconfig.new has been downloaded to your machine"
