# Reminder that the pem file should look like:
# -----BEGIN CERTIFICATE-----
# --- ... CERT CONTENT ... --
# -----END CERTIFICATE-----
# -----BEGIN CERTIFICATE-----
# --- ... INTERMEDIATE ..----
# -----END CERTIFICATE----
# -----BEGIN PRIVATE KEY-----
# --- .... PRIV KEY -----
# -----END PRIVATE KEY-----
- name: provision
  hosts: restund
  gather_facts: yes
  become: yes
  any_errors_fatal: True
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: hostname
      tags:
        - hostname

    - role: ansible-restund
      tags:
        - restund
