# TODO: Move this into a role; so we can install different containers for
# kube-master, kube-node and etcd. But this is a premature optimization as
# these are all the same nodes in our offline deploy anyway
- name: Seed docker daemon
  hosts:
    - k8s-cluster
    - etcd
  tasks:
    - name: sync containers dump to each node
      copy:
        src: ../static/containers
        dest: /var/tmp/
      when: offline
    - name: seed docker daemon
      shell: |
        for f in /var/tmp/containers/*;do
          docker load -i "$f"
        done
      when: offline

