---
# - name: Run bastion-ssh-config
#   hosts: bastion[0]
#   gather_facts: false
#   roles:
#     - { role: kubespray/kubespray-defaults }
#     - { role: kubespray/bastion-ssh-config, tags: ["localhost", "bastion"] }

- name: Copy over the binaries and debs to the bastion host and host them
  hosts: assethost
  tags:
    - debs
    - binaries
  tasks:
    - file:
        path: /opt/assets
        state: directory
    - name: Copy debs
      copy:
        src: ../debs/
        dest: /opt/assets/debs
    - name: Copy binaries
      copy:
        src: ../binaries/
        dest: /opt/assets/binaries
    - copy:
        src: files/serve-assets.service
        dest: /etc/systemd/system/serve-assets.service
    - systemd:
        name: serve-assets
        state: restarted
        enabled: yes
        daemon-reload: yes

- name: Set up offline repositories and remove online ones
  hosts: all
  tasks:
    - name: Remove /etc/apt/sources.list to remove all online debian package repos
      file:
        path: /etc/apt/sources.list
        state: absent
    - name: Register offline repo key
      apt_key:
        url: "{{ ubuntu_repo_gpgkey }}"
        state: present
    - name: Register offline repo
      apt_repository:
        repo: "deb {{ ubuntu_repo_base_url  }} bionic main"
        state: present
    - name: Apt update
      apt:
        update_cache: yes


- name: Download system containers
  hosts: k8s-cluster:etcd
  tags: system-containers
  tasks:
    - name: sync containers dump to each node
      copy:
        src: ../system-containers/
        dest: /opt/containers/

- name: Download helm containers
  hosts: k8s-cluster
  tags: helm-containers
  tasks:
    - name: download containers
      copy:
        src: ../helm-containers/
        dest: /opt/containers/

- name: Download restund container
  hosts: restund
  tags: restund-containers
  tasks:
    - name: sync container dump to each node
      synchronize:
        src: ../other-containers/quay.io_wire_restund_0.4.14w7b1.0.47.tar
        dest: /opt/containers/
        use_ssh_args: true
