on:
 - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
     - uses: actions/checkout@v2
       with:
         submodules: true
     - uses: cachix/install-nix-action@v12
     - uses: cachix/cachix-action@v7
       with:
         name: wire-server
         signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
     # TODO: shellcheck more
     - name: shellcheck
       run: $(nix-build --no-out-link -A pkgs.shellcheck)/bin/shellcheck ci.sh
     - name: build and install the environment
       run: nix-env -f default.nix -iA env
     - name: run ci.sh
       run: ./ci.sh
       env:
         # TODO: we probably only want to upload this on pushes to master, not
         # pseudo-merge commits
         DOCKER_LOGIN: '${{ secrets.DOCKER_LOGIN }}'
         GPG_PRIVATE_KEY: '${{ secrets.GPG_PRIVATE_KEY }}'
     - name: compress assets/ folder into tarball
       run: "tar cvzf assets.tgz assets"
     - name: Copy assets tarball to S3
       run: |
         aws s3 cp assets.tgz s3://public.wire.com/artifacts/wire-server-deploy-static-${{ github.sha }}.tgz
         echo "Uploaded to: https://s3-$AWS_REGION.amazonaws.com/public.wire.com/artifacts/wire-server-deploy-static-${{ github.sha }}.tgz"
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: "eu-west-1"
