on:
 - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
     - uses: actions/checkout@v2
     - uses: cachix/install-nix-action@v12
     - uses: cachix/cachix-action@v7
       with:
         name: wire-server
         signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
     # TODO: shellcheck more
     - name: shellcheck
       run: $(nix-build --no-out-link -A pkgs.shellcheck)/bin/shellcheck ci.sh
     - name: build and install the environment
       run: nix-env -f default.nix -iA env
     - name: run ci.sh
       run: ./ci.sh
       env:
         # TODO: we probably only want to upload this on pushes to master, not
         # pseudo-merge commits
         DOCKER_LOGIN: '${{ secrets.DOCKER_LOGIN }}'
         GPG_PRIVATE_KEY: '${{ secrets.GPG_PRIVATE_KEY }}'
     - uses: actions/upload-artifact@v2
       with:
         name: static
         path: static/*
