on:
 - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
     - uses: actions/checkout@v2
     - uses: cachix/install-nix-action@v11
     - uses: cachix/cachix-action@v6
       with:
         name: wire-server
         signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
     # TODO: shellcheck more
     - name: shellcheck
       run: $(nix-build --no-out-link -A pkgs.shellcheck)/bin/shellcheck ci.sh
     - name: run ci.sh
       run: ./ci.sh
       env:
         GPG_PRIVATE_KEY: '${{ secrets.GPG_PRIVATE_KEY }}'
     - uses: actions/upload-artifact@v2
       with:
         name: static
         path: static/debs/*
